title: Helsingin Choir
description: A group of Chinese scholars&students based in Helsinki, Finland
url: http://astro36.me/Materialize-Jekyll/
keywords: ["music"]
timezone: Europe/Helsinki
permalink: pretty

about: "Who are we? Where do we come from? Where are we heading?"

author:
  codepen: 
  disqus: 
  dribbble: 
  email: choir.helsinging@gmail.com
  facebook: 
  flickr: 
  foursquare: 
  github: 
  google_analytics: 
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: 
  tumblr: 
  twitter: 
  weibo: 
  xing: 
  youtube: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"

sass:
  style: compressed

include:
  - _pages