title: Helsinging Choir
title_cn: "赫声合唱团"
description: "We are a passionate singing group established in July, 2011, Helsinki, Finland. "
description_more: "Choir members are mainly young people from China."
url: 
keywords: ["music"]
timezone: Europe/Helsinki
permalink: pretty

about: "Who are we? Where do we come from? Where are we heading?"

author:
  codepen: 
  disqus: 
  dribbble: 
  email: choir.helsinging@gmail.com
  facebook: 
  flickr: 
  foursquare: 
  github: 
  google_analytics: 
  google_plus: 
  instagram: 
  lastfm: 
  linkedin: 
  name: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  telegram: 
  tumblr: 
  twitter: 
  weibo: https://m.weibo.cn/u/5149699398
  xing: 
  youtube: 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

kramdown:
  input: GFM

paginate: 5
paginate_path: "/blog/page/:num/"

sass:
  style: compressed

include:
  - _pages